#FROM : using the latest

FROM ubuntu:latest
 

RUN apt-get update && apt-get install curl -y

COPY . .

#WORKDIR 
WORKDIR /app

#COPY . .

# RUN: Install the curl 
#RUN apt-get update && apt-get install curl -y


#CMD
CMD ["sleep", "500"]

